include $(STOCHSUITE_HOME)/stochsuite.mk

clean:
	@rm -f TB-sim
	@rm -f JKISS-sim
	@rm -f Taus88-gatesim
	@rm -f sim.log
	@rm -f synth.log
	@rm -f gatesim.log
	@rm -f taus88.netlist.v
	@rm -f taus88_opt.netlist.v